#!/bin/bash
#SBATCH --job-name=oc20_FeNiCr_H2O
#SBATCH --partition=gpu_a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH --time=5:00:00
#SBATCH --error=stderr_%j
#SBATCH --output=stdout_%j

source ~/micromamba/etc/profile.d/mamba.sh
micromamba activate grace

pacemaker input.yaml --verbose-tf
