backend:
  batch_size: 50
  batch_size_reduction: 'True'
  batch_size_reduction_factor: 2
  display_step: 50
  evaluator: tensorpot
  gpu_config:
    mem_limit: 0
cutoff: 7.6
data:
  filename: /scratch-shared/zhanglei1/xpot_optimise/data/Ta.pckl.gzip
  test_size: 0.1
fit:
  loss:
    L1_coeffs: 1.0e-08
    L2_coeffs: 1.0e-08
    kappa: 0.01
    w0_rad: 1.0e-08
    w1_coeffs: 0
    w1_rad: 1.0e-08
    w2_coeffs: 0
    w2_rad: 1.0e-08
  maxiter: 2000
  optimizer: BFGS
  repulsion: auto
  trainable_parameters: ALL
metadata:
  purpose: Potential fit
potential:
  bonds:
    ALL:
      NameofCutoffFunction: cos
      dcut: 0.03131930338863473
      radbase: SBessel
      radparameters:
      - 4.436350897573117
      rcut: 7.6
  deltaSplineBins: 0.001
  elements:
  - Ta
  embeddings:
    ALL:
      drho_core_cut: 500
      fs_parameters:
      - 1
      - 1
      - 1
      - 1.2266175144413007
      ndensity: 2
      npot: FinnisSinclairShiftedScaled
      rho_core_cut: 3000
  functions:
    ALL:
      lmax_by_orders:
      - 0
      - 4
      - 3
      - 2
      - 1
      - 0
      nradmax_by_orders:
      - 15
      - 6
      - 4
      - 3
      - 2
      - 2
    number_of_functions_per_element: 101
seed: 42
